Added Prometheus auth proxy
redhat-developer/che-monitoring pull request #8
Opened 2019-05-27 13:45 UTC by skabashnyuk

Added Prometheus auth proxy
for https://github.com/redhat-developer/che-monitoring/issues/4

2019-05-27 15:09 UTC, aditya-konarde requested changes
You need a secrets reference in the pod template: 
```
    secrets:
    - app-sre-observability-htpasswd
```

2019-05-27 15:22 UTC, aditya-konarde requested changes

2019-05-27 15:22 UTC, aditya-konarde commented on openshift/che-monitoring.yaml
> +          - -upstream=${PROMETHEUS_SVC_URL}
You either need to add this as a template parameter.

Declaration in the parameters section:
https://gitlab.cee.redhat.com/service/app-sre-observability/blob/master/openshift/prometheus.template.yaml#L177-178

And then set this value in the saas file once this PR is merged: https://github.com/openshiftio/saas-openshiftio/pull/1283

2019-05-27 15:22 UTC, aditya-konarde commented
We cannot hard-code this value as the SVC URL's are different for staging and prod.

2019-05-28 08:11 UTC, ibuziuk approved these changes

2019-05-28 08:19 UTC, aditya-konarde approved these changes
LGTM

2019-05-28 08:27 UTC, merged