Repackage oauth2_proxy with rhel image
redhat-developer/che-monitoring pull request #9
Opened 2019-05-30 13:34 UTC by skabashnyuk

2019-05-30 13:38 UTC, ibuziuk commented on build_deploy.sh
> +echo 'CICO: Image pushed, ready to update deployed app'
no new line

2019-05-30 14:02 UTC, ibuziuk approved these changes

2019-05-30 14:15 UTC, aditya-konarde requested changes

2019-05-30 14:15 UTC, aditya-konarde commented on build_deploy.sh
> +  tag_push ${REGISTRY}/openshiftio/frhche-che-oauth2_proxy:latest
There's an extra `f` in the name of the image here

2019-05-30 14:15 UTC, aditya-konarde commented on build_deploy.sh
> +  tag_push ${REGISTRY}/openshiftio/frhche-che-oauth2_proxy:latest
`frhche` should be `rhche`

2019-05-31 06:56 UTC, aditya-konarde approved these changes
LGTM

2019-05-31 12:07 UTC, merged